### PR TITLE
dont display last modified date on zero value

### PR DESCRIPTION
**Pull request by twobiers**

### CODE REVIEW

**Comment by Vimux** [comment]
What is the REAL use case for setting zero for the last modified value? Why not an empty string or false?

**Comment by twobiers** [comment]
> What is the REAL use case for setting zero for the last modified value? Why not an empty string or false? Maybe I misunderstood your title, but I would like to see reproduction steps then.

yeah, should have put more information into it, sorry.
I'm using the Jekyll-like convention to generate date metadata from the filename. So I have the following Hugo config in use. 
```toml
[frontmatter]
	date = [":filename", ":default"]
```
This allows me to set filenames like `2022_04_11_helloWorld.md` and the date will be infered from the filename. However, this does also mean that there is no additional `date` field in the frontmatter required. Lastmod won't catch that and will use the `date` field from the frontmatter which is 0 by default. 

The best fix for this is probably to also configure the `lastmod` field in Hugos config, but I thought this was still worth a PR. 
```toml
[frontmatter]
	date = [":filename", ":default"]
    lastmod = [":filename", ":default", ":fileModTime"]
```

**Comment by Vimux** [comment]
Valid point. And yet, if I have the opportunity not to add code to the project, then it should be so. If you can do something with Hugo, then that's how it should be. The less additional logic in the theme, the better and easier it is to maintain.

---

Any troubles or annoying things with this?

> ```
> [frontmatter]
>	date = [":filename", ":default"]
>	lastmod = [":filename", ":default", ":fileModTime"]
> ```

**Comment by twobiers** [comment]
Yeah, sure. No, there's nothing wrong doing this.

**Pull request closed without merging**
